# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Academany
email: info@academany.org
description: > 
  The Academy of (almost) anything
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://academany.org" # the base hostname & protocol for your site

#sidebar
default-image: http://placehold.it/500x250 # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: academany
copyright:
   name: academany
   link: 'http://academany.org'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

#social
facebook: http://facebook.com/webjeda
quora: http://quora.com/sharathdt
twitter: http://twitter.com/@webjeda
github: http://github.com/webjeda

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/webjeda/
fb-page-title: webjeda

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]


partners:
  - title: Fab Foundation
    url: http://fabfoundation.org
  - title: FabLabs.io
    url: http://fablabs.io
  - title: MIT Center for Bits and Atoms
    url: http://cba.mit.edu
    
websites:
  - title: Fab Academy
    url: http://fabacademy.org
  - title: Bio Academy
    url: http://bio.academany.org
  - title: Fabricademy
    url: http://textile-academy.org/bootcamp
